In [1]:
import streamlit as st
import seaborn as sns
import plotly.express as px
import pandas as pd 
import plotly.graph_objects as go
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(r"C:\Users\ASUS\OneDrive\Desktop\DA1 Project\Latest Covid-19 India Status.csv")

df

,State/UTs,Total Cases,Active,Discharged,Deaths,Active Ratio,Discharge Ratio,Death Ratio,Population
0,Andaman and Nicobar,10766,0,10637,129,0.00,98.80,1.20,100896618
1,Andhra Pradesh,2340676,0,2325943,14733,0.00,99.37,0.63,128500364
2,Arunachal Pradesh,67049,0,66753,296,0.00,99.56,0.44,658019
3,Assam,746159,5,738119,8035,0.00,98.92,1.08,290492
4,Bihar,855267,1,842952,12314,0.00,98.56,1.44,40100376
5,Chandigarh,100693,0,99508,1185,0.00,98.82,1.18,30501026
6,Chhattisgarh,1187695,0,1173505,14190,0.00,98.81,1.19,28900667
7,Dadra and Nagar Haveli and Daman and Diu,11592,0,11588,4,0.00,99.97,0.03,231502578
8,Delhi,2040910,14,2014230,26666,0.00,98.69,1.31,773997
9,Goa,263346,3,259329,4014,0.00,98.47,1.52,3772103
10,Gujarat,1291383,5,1280299,11079,0.00,99.14,0.86,70400153
11,Haryana,1078903,27,1068121,10755,0.00,99.00,1.00,7503010
12,Himachal Pradesh,322905,4,318660,4241,0.00,98.69,1.31,3436948
13,Jammu and Kashmir,482023,0,477231,4792,0.00,99.01,0.99,66001
14,Jharkhand,443826,1,438491,5334,0.00,98.80,1.20,124904071
15,Karnataka,4088769,12,4048399,40358,0.00,99.01,0.99,1711947
16,Kerala,6907241,18,6835181,72042,0.00,98.96,1.04,91702478
17,Ladakh,29602,0,29371,231,0.00,99.22,0.78,4184959
18,Lakshadweep,11415,0,11363,52,0.00,99.54,0.46,11700099
19,Madhya Pradesh,1056351,0,1045565,10786,0.00,98.98,1.02,14999397
20,Maharashtra,8171048,214,8022276,148558,0.00,98.18,1.82,399001
21,Manipur,140034,0,137885,2149,0.00,98.47,1.53,47099270
22,Meghalaya,96983,3,95352,1628,0.00,98.32,1.68,79502477
23,Mizoram,239560,1,238825,734,0.00,99.69,0.31,1308967
24,Nagaland,36033,0,35251,782,0.00,97.83,2.17,38157311
25,Odisha,1348409,59,1339135,9215,0.00,99.31,0.68,19301096
26,Puducherry,177547,0,175566,1981,0.00,98.88,1.12,2073074
27,Punjab,793644,1233,773073,19338,0.16,97.41,2.44,34698876
28,Rajasthan,1326465,2,1316727,9736,0.00,99.27,0.73,1521992
29,Sikkim,44927,4,44422,501,0.01,98.88,1.12,83697770
30,Tamil Nadu,3610655,5,3572569,38081,0.00,98.95,1.05,35998752
31,Telengana,844432,8,840313,4111,0.00,99.51,0.49,69599762
32,Tripura,108493,1,107550,942,0.00,99.13,0.87,1646050
33,Uttar Pradesh,2145431,57,2121662,23712,0.00,98.89,1.11,1158040
34,Uttarakhand,452571,0,444803,7768,0.00,98.28,1.72,85002417
35,West Bengal,2126282,135,2104592,21555,0.01,98.98,1.01,32199722